FROM public.ecr.aws/lambda/python:3.8




# Install the function's dependencies using file requirements.txt
# from your project folder.


# WIS2 monitoring library

#COPY wis2mon-lib-import /tmp/wis2mon-lib-import	
#RUN pip3 install /tmp/wis2mon-lib-import

# Copy function code
COPY lambda_s3tords/app.py ${LAMBDA_TASK_ROOT}
COPY lambda_s3tords/s3tords.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "app.lambda_handler" ] 